version: '3'

services:

  php:
    container_name: app
    image: marcelofabianov/php-8.1-fpm-dbs
    restart: always
    working_dir: /var/www/html
    environment:
      TZ: '${TZ:-}'
    volumes:
      - .:/var/www/html
    ports:
      - "9999:9000"
    networks:
      - app_network

  http:
    container_name: http
    image: nginx:latest
    restart: always
    environment:
      TZ: '${TZ:-}'
    ports:
      - "8008:80"
      - "333:443"
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/local/http/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/local/http/logs:/var/log/nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge